name: Generate IV Surfaces
on:
  schedule:
    - cron: "0 0 */2 * *"  # Every 2 days at midnight
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate IV Surfaces
      run: |
        python scripts/html_creation.py

    - name: Commit and push results
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/data/
        git commit -m "Auto-update IV surfaces on $(date +'%Y-%m-%d')"
        git push